# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/GUNDA/AppData/Local/Temp/mainuwXumb.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from SanskritNames import months
import add_sevadar_page
import display_sevadars
import overview
import end_dates
from cloud import drive_upload
from PyQt5 import QtCore, QtGui, QtWidgets




class Ui_MainWindow(object):
    def __init__(self,MainWindow) -> None:
        super().__init__()
        self.setupUi(MainWindow)
        self.retranslateUi(MainWindow)
        self.add_options(MainWindow)
        self.connectUi(MainWindow)
        self.MainWindow = MainWindow

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(270, 110, 251, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.add_sevadar_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.add_sevadar_button.setObjectName("add_sevadar_button")
        self.verticalLayout.addWidget(self.add_sevadar_button)
        self.display_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.display_button.setObjectName("display_button")
        self.verticalLayout.addWidget(self.display_button)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(270, 250, 251, 96))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.horizontalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(9, -1, 7, -1)
        self.horizontalLayout.setSpacing(13)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.month_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.month_label.setObjectName("month_label")
        self.horizontalLayout.addWidget(self.month_label)
        self.month_comboBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.month_comboBox.setEditable(False)
        self.month_comboBox.setMaxVisibleItems(12)
        self.month_comboBox.setIconSize(QtCore.QSize(20, 20))
        self.month_comboBox.setObjectName("month_comboBox")
        self.horizontalLayout.addWidget(self.month_comboBox)
        self.year_label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.year_label.setObjectName("year_label")
        self.horizontalLayout.addWidget(self.year_label)
        self.year_spinBox = QtWidgets.QSpinBox(self.horizontalLayoutWidget)
        self.year_spinBox.setMinimum(2000)
        self.year_spinBox.setMaximum(9999)
        self.year_spinBox.setProperty("value", 2021)
        self.year_spinBox.setDisplayIntegerBase(10)
        self.year_spinBox.setObjectName("year_spinBox")
        self.horizontalLayout.addWidget(self.year_spinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.download_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.download_button.setObjectName("download_button")
        self.verticalLayout_2.addWidget(self.download_button)
        self.view_end_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.view_end_button.setObjectName("view_end_button")
        self.verticalLayout_2.addWidget(self.view_end_button)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 30, 251, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.cloud_backup_button = QtWidgets.QPushButton(self.centralwidget)
        self.cloud_backup_button.setGeometry(QtCore.QRect(310, 390, 181, 31))
        self.cloud_backup_button.setObjectName("cloud_backup_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.add_sevadar_button.setText(_translate("MainWindow", "Add sevadar"))
        self.display_button.setText(_translate("MainWindow", "View/Edit details"))
        self.month_label.setText(_translate("MainWindow", "Month"))
        self.year_label.setText(_translate("MainWindow", "Year"))
        self.download_button.setText(_translate("MainWindow", "Download pdf"))
        self.view_end_button.setText(_translate("MainWindow", "View End months"))
        self.label.setText(_translate("MainWindow", "Seva Manager"))
        self.cloud_backup_button.setText(_translate("MainWindow", "Cloud backup (Google drive)"))

    def add_options(self,MainWindow):
        self.month_comboBox.addItems(months.values())
    
    def connectUi(self,MainWindow):
        self.add_sevadar_button.clicked.connect(self.add_callback)
        self.display_button.clicked.connect(self.display_callback)
        self.download_button.clicked.connect(self.overview_callback)
        self.cloud_backup_button.clicked.connect(drive_upload)
        self.view_end_button.clicked.connect(self.view_end_callback)



    def add_callback(self):
        print("add")
        add_window = QtWidgets.QMainWindow()
        ui = add_sevadar_page.Ui_MainWindow(add_window)
        add_window.showMaximized()
        
    def display_callback(self):
        print("display")
        ui = display_sevadars.App()

    def overview_callback(self):
        print("overview")
        year = self.year_spinBox.value()
        month = self.month_comboBox.currentIndex()+1
        ui = overview.App(year,month)

    def view_end_callback(self):
        print("view end")
        year = self.year_spinBox.value()
        month = self.month_comboBox.currentIndex()+1
        ui = end_dates.App(year,month)
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    # x = QtWidgets.QAbstractScrollArea()
    ui = Ui_MainWindow(MainWindow)
    # ui.setupUi()
    MainWindow.showMaximized()
    sys.exit(app.exec_())